version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adventurehub
    ports:
        - "3306:3306"
  api:
    build:
      context: .
      dockerfile: src/main/resources/docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
        - db